# Generated by Django 2.2.5 on 2019-09-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190908_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='tickets',
            new_name='seats',
        ),
    ]
