# Generated by Django 2.2.5 on 2019-09-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='organizer',
        ),
    ]
