# Generated by Django 2.2.5 on 2019-09-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190908_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='events.Event'),
        ),
    ]
